format_version: v1.0
type: UniqueComponent
attributes: {id: a_i2s}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: I2S_CLKCTRL_0_CLKMODE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Integer
    attributes: {id: I2S_CLKCTRL_0_MCKDIV}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: I2S_CLKCTRL_0_MCKOUTDIV}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: I2S_CLKCTRL_0_SLOTSIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: KeyValueSet
    attributes: {id: I2S_LRCLK_INVERT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: I2S_RX_SERIALIZER_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: KeyValueSet
    attributes: {id: I2S_TXCTRL_DATASIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
- type: ElementPosition
  attributes: {x: '535', y: '436', id: a_i2s}
